# Generated by Django 2.2.2 on 2022-04-08 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='message_is_opened',
            field=models.BooleanField(default=False),
        ),
    ]
