# Generated by Django 2.2.2 on 2022-06-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_listnavigator'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='branch_ID',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
