# Generated by Django 2.2.2 on 2022-06-17 10:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_chatmessage_branch_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_ID', models.CharField(default='none', max_length=50)),
                ('business_ID', models.CharField(default='none', max_length=50)),
                ('supportAgent_ID', models.CharField(default='none', max_length=50)),
                ('supportAgent', models.CharField(default='none', max_length=50)),
                ('addNoteName', models.CharField(default='none', max_length=500)),
                ('addNoteDetails', models.TextField(default='none')),
                ('Notetag', models.CharField(default='none', max_length=500)),
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
