# Generated by Django 2.2.2 on 2022-06-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_addnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='media_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/'),
        ),
    ]
