# Generated by Django 2.2.2 on 2022-08-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_chatmessage_media_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_ID', models.CharField(default='none', max_length=50)),
                ('branch_ID', models.CharField(default='none', max_length=50)),
                ('business_ID', models.CharField(default='none', max_length=50)),
                ('message_ID', models.CharField(default='none', max_length=50)),
                ('media_file', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d/')),
                ('media_type', models.CharField(default='none', max_length=20)),
                ('media_available', models.BooleanField(default=False)),
            ],
        ),
    ]
