# Generated by Django 2.2.2 on 2024-10-09 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_remove_customermedia_media_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ListNavigator',
        ),
        migrations.DeleteModel(
            name='Navigator',
        ),
    ]
