# Generated by Django 2.2.2 on 2024-03-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_name', models.CharField(default='', max_length=500)),
                ('member_comment', models.TextField(default='', max_length=5000)),
                ('postID', models.CharField(default='', max_length=500)),
                ('up_vote_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.TextField(default='', max_length=5000)),
                ('postID', models.CharField(default='', max_length=500)),
                ('comments', models.IntegerField(default=0)),
                ('up_vote_count', models.IntegerField(default=0)),
            ],
        ),
    ]
