# Generated by Django 2.2.2 on 2024-03-13 11:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('non_profit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='dateadded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='forum',
            name='dateadded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
