# Generated by Django 2.2.2 on 2024-10-09 12:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('non_profit', '0002_auto_20240313_1305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Joined_Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_ID', models.CharField(default='', max_length=500)),
                ('topic_ID', models.CharField(default='', max_length=500)),
                ('topic_status', models.CharField(default='', max_length=500)),
                ('member_first_name', models.CharField(default='', max_length=20)),
                ('member_last_name', models.CharField(default='', max_length=20)),
                ('mobile_number', models.CharField(default='', max_length=20)),
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='member_name',
            new_name='business_ID',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='postID',
            new_name='topic_ID',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='postID',
            new_name='business_ID',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='topic',
            new_name='topic_description',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='comments',
            new_name='total_comments',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='up_vote_count',
            new_name='total_members',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='up_vote_count',
        ),
        migrations.AddField(
            model_name='comment',
            name='member_first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='comment',
            name='member_last_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='comment',
            name='topic_status',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='forum',
            name='topic_ID',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='forum',
            name='topic_status',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='forum',
            name='topic_title',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
