# Generated by Django 2.2.2 on 2024-10-09 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_profit', '0003_auto_20241009_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='topic_thubnail',
            field=models.FileField(blank=True, null=True, upload_to='forum/%Y/%m/%d/'),
        ),
    ]
