# Generated by Django 2.2.2 on 2024-10-13 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('non_profit', '0004_forum_topic_thubnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_ID', models.CharField(default='', max_length=500)),
                ('topic_ID', models.CharField(default='', max_length=500)),
                ('category_ID', models.CharField(default='', max_length=500)),
                ('category', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Our_Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_ID', models.CharField(default='', max_length=500)),
                ('project_ID', models.CharField(default='', max_length=500)),
                ('project_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_tittle', models.CharField(default='', max_length=200)),
                ('project_description', models.TextField(default='', max_length=5000)),
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_ID', models.CharField(default='', max_length=500)),
                ('topic_ID', models.CharField(default='', max_length=500)),
                ('topic_tittle', models.CharField(default='', max_length=200)),
                ('description', models.TextField(default='', max_length=5000)),
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TopicMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_ID', models.CharField(default='', max_length=500)),
                ('topic_ID', models.CharField(default='', max_length=500)),
                ('media', models.FileField(blank=True, null=True, upload_to='forum/%Y/%m/%d/')),
                ('file_type', models.CharField(choices=[('Document', 'Document'), ('Image', 'Image'), ('Video', 'Video'), ('Audio', 'Audio')], default='Document', max_length=50)),
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(default='Self', max_length=5000),
        ),
        migrations.AlterField(
            model_name='forum',
            name='topic_status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('CLOSED', 'CLOSED')], default='ACTIVE', max_length=500),
        ),
    ]
