# Generated by Django 2.2.2 on 2024-10-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_profit', '0005_auto_20241013_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='our_projects',
            name='project_thubnail',
            field=models.FileField(blank=True, null=True, upload_to='forum/%Y/%m/%d/'),
        ),
    ]
