# Generated by Django 2.2.2 on 2024-10-14 16:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('non_profit', '0006_our_projects_project_thubnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectMedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_ID', models.CharField(default='', max_length=500)),
                ('project_ID', models.CharField(default='', max_length=500)),
                ('project_media', models.FileField(blank=True, null=True, upload_to='projects/%Y/%m/%d/')),
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
