# Generated by Django 2.2.2 on 2024-10-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_profit', '0007_projectmedia'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
