# Generated by Django 2.2.2 on 2024-10-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_profit', '0008_topic_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmedia',
            name='file_size',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='topicmedia',
            name='file_type',
            field=models.CharField(default='', max_length=50),
        ),
    ]
