# Generated by Django 2.2.2 on 2024-10-16 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_profit', '0009_auto_20241016_1735'),
    ]

    operations = [
        migrations.AddField(
            model_name='topicmedia',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
