# Generated by Django 2.2.2 on 2024-10-17 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_profit', '0011_topicmedia_file_extension'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicmedia',
            name='file_size',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
