# Generated by Django 2.2.2 on 2024-10-28 15:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('non_profit', '0012_auto_20241017_0517'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_ID', models.CharField(default='', max_length=500)),
                ('partner_organisation', models.CharField(default='', max_length=500)),
                ('partner_type', models.CharField(default='', max_length=5000)),
                ('partner_thubnail', models.FileField(blank=True, null=True, upload_to='partner/%Y/%m/%d/')),
                ('description', models.TextField(default='', max_length=5000)),
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Partner_Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_ID', models.CharField(default='', max_length=500)),
                ('partner_organisation', models.CharField(default='', max_length=500)),
                ('partner_type', models.CharField(default='', max_length=5000)),
                ('partner_request_status', models.CharField(default='', max_length=5000)),
                ('description', models.TextField(default='', max_length=5000)),
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
