# Generated by Django 2.2.2 on 2024-10-31 15:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('non_profit', '0013_partner_partner_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Q_Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_ID', models.CharField(default='', max_length=500)),
                ('question_ID', models.CharField(default='', max_length=500)),
                ('answer', models.TextField(default='', max_length=5000)),
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_ID', models.CharField(default='', max_length=500)),
                ('question_ID', models.CharField(default='', max_length=500)),
                ('question', models.TextField(default='', max_length=5000)),
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Question_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_ID', models.CharField(default='', max_length=500)),
                ('question_ID', models.CharField(default='', max_length=500)),
                ('category', models.CharField(default='', max_length=500)),
                ('dateadded', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
