# Generated by Django 2.2.2 on 2024-10-31 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('non_profit', '0014_q_answer_question_question_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='', max_length=500),
        ),
    ]
