# Generated by Django 2.2.2 on 2021-09-05 13:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controlCentre', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Instance_ID', models.CharField(default='None', max_length=50)),
                ('Instance_IP', models.CharField(max_length=50)),
                ('Port', models.CharField(default='---', max_length=250)),
                ('instanceUser', models.CharField(default='None', max_length=250)),
                ('instancePassword', models.CharField(default='None', max_length=250)),
                ('SSH_Key', models.CharField(default='None', max_length=250)),
                ('assinged_status', models.BooleanField(default=False)),
                ('portal_installed', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.RenameField(
            model_name='schoolportalimage',
            old_name='assinged_status',
            new_name='BillingAccount_active_status',
        ),
        migrations.RenameField(
            model_name='schoolportalimage',
            old_name='package',
            new_name='Instance_ID',
        ),
        migrations.RenameField(
            model_name='schoolportalimage',
            old_name='portal_active_status',
            new_name='Instance_assinged_status',
        ),
        migrations.RemoveField(
            model_name='schoolportalimage',
            name='IpAdress',
        ),
        migrations.RemoveField(
            model_name='schoolportalimage',
            name='NextbillingStartsOn',
        ),
        migrations.RemoveField(
            model_name='schoolportalimage',
            name='SchoolPortalImage_ID',
        ),
        migrations.RemoveField(
            model_name='schoolportalimage',
            name='active_status_since',
        ),
        migrations.RemoveField(
            model_name='schoolportalimage',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='schoolportalimage',
            name='billingStartedOn',
        ),
        migrations.RemoveField(
            model_name='schoolportalimage',
            name='default_url',
        ),
        migrations.RemoveField(
            model_name='schoolportalimage',
            name='instancePassword',
        ),
        migrations.RemoveField(
            model_name='schoolportalimage',
            name='instanceUser',
        ),
        migrations.RemoveField(
            model_name='schoolportalimage',
            name='port',
        ),
        migrations.AddField(
            model_name='schoolportalimage',
            name='Instance_IP',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='schoolportalimage',
            name='Port',
            field=models.CharField(default='---', max_length=250),
        ),
    ]
