# Generated by Django 2.2.2 on 2022-09-25 20:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controlCentre', '0002_auto_20210905_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_ID', models.CharField(default='None', max_length=50)),
                ('business_Name', models.CharField(default='None', max_length=50)),
                ('emailCounter', models.IntegerField(default=1)),
                ('Price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('suspend_status', models.BooleanField(default=False)),
                ('first_billing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('second_billing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('third_billing_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('account_suspension_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
