# Generated by Django 2.2.2 on 2022-09-26 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlCentre', '0003_billingmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmanager',
            name='billing_Name',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
