# Generated by Django 2.2.2 on 2022-09-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlCentre', '0004_billingmanager_billing_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmanager',
            name='first_billing_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingmanager',
            name='forth_billing_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingmanager',
            name='second_billing_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='billingmanager',
            name='third_billing_status',
            field=models.BooleanField(default=False),
        ),
    ]
