# Generated by Django 2.2.2 on 2022-09-26 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('controlCentre', '0005_auto_20220926_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingmanager',
            name='forth_billing_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
